# Generated by Django 6.0.2 on 2026-02-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Tarjeta', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Tarjeta')),
                ('nombre_Usuario', models.CharField(max_length=100, verbose_name='Nombre del Usuario')),
                ('rol_Usuario', models.CharField(max_length=50, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id_Acceso', models.AutoField(primary_key=True, serialize=False)),
                ('estado_Acceso', models.CharField(max_length=20, verbose_name='Estado de Acceso')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_rfid.usuario')),
            ],
        ),
    ]
